<?php

/**
 * Implements hook_views_api().
 */
function italomairo_views_views_api() {
    return array(
        'api' => '3.0',
    );
}

/**
 * Implements hook_views_default_views().
 */
function italomairo_views_views_default_views() {
    $path = './' . drupal_get_path('module', 'italomairo_views') . '/views/*.inc';
    $views = array();
    foreach (glob($path) as $views_filename) {
        require_once($views_filename);
    }
    return $views;
}

drupal_add_css(drupal_get_path('module', 'italomairo_views') .'/italomairo_views.css');
