<?php

drupal_add_css(drupal_get_path('module', 'my_webforms') .'/css/my_webforms.css');

/**
 * Implements hook_webform menu().
 */
function my_webforms_menu() {

	$items['admin/getmyprivacy'] = array(
		     'page callback' => 'getmyprivacy',
		     'type' => MENU_CALLBACK,
		     'access arguments' => array('access content'),
	       );
	     return $items;
	     }
	
	
/**
 * Implements hook_form_alter().
 */
function my_webforms_form_alter(&$form, &$form_state, $form_id) {
	
	//dpm($form_id);
	
	//hook newsletter 
	if($form_id=='webform_client_form_27'){
		$form['#validate'][]='my_webforms_form_newsletter_validate';//hook di validazione al momento della sottoscrizione di una newsletter
	}
	//hook newsletter unsubscribe
	if($form_id=='webform_client_form_867') {
		$form['#validate'][]='my_webforms_form_validate_unsubscribe';//hook di validazione al momento della sottoscrizione di una newsletter
	}
	
	//hook richiedi copia gratuita
	if($form_id=='webform_client_form_607'){
		$form['#validate'][]='my_webforms_form_copia_gratuita_validate';//hook di validazione al momento della richiesta di copia gratuita
	}
	
	$mywebforms_params = array(
		'webform_client_form_607'=>array("submitted"=>"rivista"),
		'webform_client_form_27'=>array("submitted"=>"newsletter"),
		'webform_client_form_608' => array("submitted"=>"prodotto")
        );
	
	if (array_key_exists($form_id, $mywebforms_params)) {
		drupal_add_js(drupal_get_path('module', 'my_webforms') .'/js/my_webforms.js', "file");
		if (isset ($form['submitted']['termini_e_condizioni']) ) {
			$form['submitted']['termini_e_condizioni']['accetto_i_termini_e_le_condizioni']['#title'] = t('');
			$form['submitted']['termini_e_condizioni']['accetto_comunicazione_dati_personali']['#title'] = t('');
			$comunicazione_dati_personali = $form['submitted']['termini_e_condizioni']['comunicazione_dati_personali']['#markup'];
			$form['submitted']['termini_e_condizioni']['comunicazione_dati_personali']['#markup'] = '<br>'.t($comunicazione_dati_personali);
		}
    
		//if (isset ($form['submitted']['richiesta']['rivista']) ) {
		//$form['submitted']['richiesta']['rivista']['#title'] = t('');
		// }
		
	//Validazione/alterazione dei campi sui telefoni (che se senza suffisso nn vengono esportati bene in excel, in quanto omette eventuale 0 del prefisso telefonico nel formato cella generale
	$form['#validate'][] = 'my_phone_numbers_form_validate'; 	
	
	}
	
	//hook webform_results_download_form
	if($form_id=='webform_results_download_form') {
		
		$form['format']['#default_value'] = 'excel';
		$form['format']['#attributes']['disabled'] = 'TRUE';
		$form['select_options']['select_keys']['#default_value'] = 1;
		$form['select_options']['#collapsible'] = 'FALSE';
		$form['select_options']['select_keys']['#attributes']['disabled'] = 'TRUE';
		$form['range']['#collapsible'] = 'FALSE';
		$form['range']['range_type']['#default_value'] = 'new';
		unset($form['components']['#options']['uid']); unset($form['components']['#default_value'][6]);
		unset($form['components']['#options']['draft']); unset($form['components']['#default_value'][4]);
		unset($form['components']['#options']['username']); unset($form['components']['#default_value'][7]);
		//dpm($form);
	}	

}


function my_webforms_node_view($node, $view_mode, $langcode){
	//dpm($node);
	drupal_add_js(drupal_get_path('module', 'my_webforms') .'/js/my_webforms.js', "file");
	drupal_add_library('system', 'ui.dialog');
}

function getmyprivacy(){

	$nid = 852;// nid pagina privacy
	print drupal_render(node_view(node_load($nid),'full',$_GET['ln']));

	}
function my_webforms_webform_submission_insert($node, $submission){
	/*nid=867 webform unsubscribe*/
	if($submission->nid==867){
		$email=$submission->data[4][0];
		$oggettoRichiesta=$submission->data[16][0];
		$stato=0;/*cid 23 cancellazione logica*/
		$nid_webform_scelta=27;
		module_load_include('inc', 'webform', 'includes/webform.submissions');	
		//$email='marcoromano12@gmail.com';
		//$oggettoRichiesta='Food and Beverage';
		/*seleziono tutte le mie sottoscrizioni alle newsletter*/
		$querystring="SELECT sid FROM webform_submitted_data WHERE nid=27 AND data='".$email."' AND nid=".$nid_webform_scelta;
		$result = db_query($querystring);
		if($result->rowCount()==0) {
			return;
		}
		foreach($result as $row){
			$fr=webform_get_submissions(array('nid' => $nid_webform_scelta,'sid' =>$row->sid));
			/*prendo solo i sid delle newsletter da me selezionata nel webform*/
			if($fr[$row->sid]->data[16][0]==$oggettoRichiesta)
				$array_sid[]=$row->sid;
		}
		if (!empty($array_sid)) {
			$array_in=implode(",",$array_sid);
			$queryupdate="UPDATE webform_submitted_data SET data='".$stato."' WHERE cid=23 AND data='1' AND sid IN (".$array_in.")";
			$result = db_query($queryupdate);
		}
	}
	
	/*nid=607 indica sottoscrizione a RICHIEDI COPIA GRATUTITA
		questa richiesta implicherà la sottoscrizione automatica alle newsletter associate alla rivista scelta
	*/
	if($submission->nid==607){
		global $user;
		/*Valori submission copia gratutita*/
		$oggettoRichiesta=$submission->data[16][0];// Oggetto della richiesta
		$nome=$submission->data[1][0];// Nome
		$cognome=$submission->data[2][0];// cognome
		$email=$submission->data[4][0];//email
		$tipo=$submission->data[6][0];//tipo
		$rsociale=$submission->data[7][0];// rag sociale
		$tel=$submission->data[9][0];// tel
		$cell=$submission->data[10][0];// cell
		$fax=$submission->data[11][0];// fax
		$accetto1=$submission->data[13][0];// Accetto i termini e le condizioni
		$accetto2=$submission->data[22][0];// Accetto i termini e le condizioni
		
		//nodonid iscrizione newslettere= 27
		$nidRichiestaNewsletter=27;
		//drupal_set_message($oggettoRichiesta);
		//drupal_set_message($submission->data[16][0]);
		//dpm($submission);
		//dpm($node);

		$query = new EntityFieldQuery();
		 $query->entityCondition('entity_type', 'node')
		  ->entityCondition('bundle', 'rivista')
		  ->propertyCondition('title', $oggettoRichiesta)
		  ->execute();
		//$title_is_unique = empty($result['node']);
		$result = $query->execute();
		if (!empty($result['node'])) {
			$id_my_rivista = array_keys($result['node']);
			$my_rivista=node_load($id_my_rivista[0]);
			//dpm($my_rivista);
			$item_newsletter_correlata = field_get_items('node', $my_rivista, 'field_newsletter_correlata');	
			$array_new_correlate=null;
			foreach ($item_newsletter_correlata as $k=>$n){
				$array_new_correlate[]=$item_newsletter_correlata[$k]['tid'];
			}
			if (!empty($array_new_correlate)) {
				foreach ($array_new_correlate as $value) {
					$term = taxonomy_term_load($value);
					$data = array(
						'16' => array($term->name),
						'1' => array($nome),
						'2' => array($cognome),
						'4' => array($email),
						'6' => array($tipo),
						'7' => array($rsociale),
						'9' => array($tel),
						'10' => array($cell),
						'11' => array($fax),
						'13' => array($accetto1),
						'22' => array($accetto2),
						'23' => array(1),
					);

					$submission = (object) array(
						'nid' => $nidRichiestaNewsletter,
						'uid' => $user->uid,
						'submitted' => REQUEST_TIME,
						'remote_addr' => ip_address(),
						'is_draft' => FALSE,
						'data' => $data,
					);
					$nodeTemp=node_load($nidRichiestaNewsletter);
					$array_controllo=array(array('cid'=>'16','value'=>$term->name),array('cid'=>'23','value'=>1));
					$esito=my_validation($nidRichiestaNewsletter,$email,$array_controllo);
					if($esito){
						webform_submission_insert($nodeTemp, $submission);
						//drupal_set_message($term->name . "sottoscritta");
					}else{
						//drupal_set_message($term->name . "NON sottoscritta");
					}
					//webform_submission_send_mail($node, $submission);
				}
			
			}
			
			//dpm($array_new_correlate);
		}
	}
	
	
}
function my_webforms_form_validate_unsubscribe($form,&$form_state){
		//dpm($form);
		//dpm($form_state);
		module_load_include('inc', 'webform', 'includes/webform.submissions');	
		$email=$form_state['values']['submitted']['dati_personali']['email'];
		$oggettoRichiesta=$form_state['values']['submitted']['richiesta']['newsletter'];
		$stato=1;
		$nid_webform_scelta=27;
		$querystring="SELECT sid FROM webform_submitted_data WHERE nid=27 AND data='".$email."' AND nid=".$nid_webform_scelta;
		$result = db_query($querystring);
		if($result->rowCount()==0) {
			$sottoscrizione_esistente="We are sorry but there is not subscription with this email address to the newsletter " ;
			form_set_error(" ",'<span class="submissionexixt"><span class="errorvalidate">'.t($sottoscrizione_esistente).': '.$form_state['values']['submitted']['richiesta']['newsletter'].'</span></span>');
		}
		foreach($result as $row){
			$fr=webform_get_submissions(array('nid' => $nid_webform_scelta,'sid' =>$row->sid));
			if($fr[$row->sid]->data[16][0]==$oggettoRichiesta && $fr[$row->sid]->data[23][0]==$stato)
				return;
		}
		$sottoscrizione_esistente="We are sorry but there is not subscription with this email address to the newsletter " ;
		form_set_error(" ",'<span class="submissionexixt"><span class="errorvalidate">'.t($sottoscrizione_esistente).': '.$form_state['values']['submitted']['richiesta']['newsletter'].'</span></span>');
		
}

function my_webforms_form_newsletter_validate($form,&$form_state) {
		////dpm($form);
		//dpm($form_state);
		//dpm($form_state['values']['submitted']);
		//$value_cid_webform=$form_state->data[16][0];
		//dpm(isset($form_state['values']['submitted']['stato']));
		$form_state['values']['submitted']['stato'] = (isset($form_state['values']['submitted']['stato'])) ? $form_state['values']['submitted']['stato'] : '1';
		$dato_webform_univoco=$form_state['values']['submitted']['dati_personali']['email'];
		$stato=1;// corrisponde al cid 23
		//$value_cid_webform=taxonomy_get_term_by_name($form_state['values']['submitted']['richiesta']['newsletter'], 9) ;// corrisponde al cid 16 - VId Newsletter = 9
		$value_cid_webform=$form_state['values']['submitted']['richiesta']['newsletter'];// corrisponde al cid 16 - VId Newsletter = 9
		$array_controllo=array(array('cid'=>'16','value'=>$value_cid_webform),array('cid'=>'23','value'=>$stato));
		$nid_webform_scelta=$form_state['build_info']['args'][0]->nid;//27 nel caso di newsletter
		$sottoscrizione_esistente="We are sorry but there is already a subscription with this email address to the newsletter " ;
	
		//dpm($form_state['input']['details']['sid']);
		$esito = (!$form_state['input']['details']['sid']) ? my_validation($nid_webform_scelta,$dato_webform_univoco,$array_controllo) : 1;
		//drupal_set_message('nid webform'.$nid_webform_scelta);
		//drupal_set_message('email'.$dato_webform_univoco);
		//drupal_set_message('Array'.$array_controllo);
		//dpm($array_controllo);
		if(!$esito)
		{//se true vuol dire che esiste già la sottoscrizione
			form_set_error(" ",'<span class="submissionexixt">'.t($sottoscrizione_esistente).': '.$form_state['values']['submitted']['richiesta']['newsletter'].'</span>');
		}
	  }
	  
function my_webforms_form_copia_gratuita_validate ($form,&$form_state) {
	//dpm($form_state);
	$form_state['values']['submitted']['copie'] = (isset($form_state['values']['submitted']['copie'])) ? $form_state['values']['submitted']['copie'] : '1';
	}

function my_phone_numbers_form_validate($form,&$form_state) {
		////dpm($form);
		//dpm($form_state);
		if (substr($form_state['values']['submitted']['dati_personali']['telefono'], 0, 1) != '#') $form_state['values']['submitted']['dati_personali']['telefono'] = '#'.$form_state['values']['submitted']['dati_personali']['telefono'];
		if (substr($form_state['values']['submitted']['dati_personali']['cellulare'], 0, 1) != '#') $form_state['values']['submitted']['dati_personali']['cellulare'] = '#'.$form_state['values']['submitted']['dati_personali']['cellulare'];
		if (substr($form_state['values']['submitted']['dati_personali']['fax'], 0, 1) != '#') $form_state['values']['submitted']['dati_personali']['fax'] = '#'.$form_state['values']['submitted']['dati_personali']['fax'];
	  }	  
	  
	  
/*
cid 23   	stato
cid 4 	 	email
cid 16 	 	newsletter (scelta)
*/
function my_validation($nid_webform_scelta,$dato_webform_univoco,$array_controllo){
	/*
	$value_cid_webform=84; tid della newsletter
	$nid_webform_scelta=27;

	$dato_webform_univoco='gino@g.it';
	$array_controllo=array(array('cid'=>16,'value'=>$value_cid_webform),array('cid'=>23,'value'=>1));
	*/
	$querystring="SELECT ws.sid as sid FROM webform_submissions ws inner join webform_submitted_data wsd on wsd.sid=ws.sid WHERE wsd.cid=4 AND wsd.data='".$dato_webform_univoco."' AND ws.nid=".$nid_webform_scelta;
	$result = db_query($querystring);
	module_load_include('inc', 'webform', 'includes/webform.submissions');

	$submit_trovata=false;
	if($result->rowCount()==0) {
	
		return true;
	}
	foreach($result as $row)
	{	
		//echo " - ".$row->sid ;
		//dpm($row->sid);
		$fr=webform_get_submissions(array('nid' => $nid_webform_scelta,'sid' =>$row->sid));
		$condition=null;
		foreach($array_controllo as $key => $val) 
		{ 
		  $condition[]='("'.$fr[$row->sid]->data[$array_controllo[$key]['cid']][0].'"=="'.$array_controllo[$key]['value'].'") ' ;
		}
		
		$myif=' return  '.implode(" && ",$condition).";";
		if(eval($myif))
		{	//sottoscrizione trovata 
			//controllo che la newsletter è ancora attiva, e update 0 qui questa
			$submit_trovata=true;
			return !$submit_trovata;
		}
		
	}
	return !$submit_trovata;
}


