<?php

drupal_add_css(drupal_get_path('module', 'my_webforms') .'/css/my_webforms.css');
	
	
/**
 * Implements hook_form_alter().
 */
function my_webforms_form_alter(&$form, &$form_state, $form_id) {
	
	
	if( $form_id == 'webform_client_form_188') {
		//dpm($form_id);
		unset($form['submitted']['object']['#size']);
		if(arg(2) == 'request_info_for') {
			
			
			$form['submitted']['object']['#default_value'] = t('Info request for ').arg(4);
		//dpm($form);
		}
	}
	
}


