<?php

drupal_add_css(drupal_get_path('module', 'my_webforms') .'/css/my_webforms.css');

/**
 * Implements hook_webform menu().
 */
function my_webforms_menu() {

	$items['admin/getmyprivacy'] = array(
		     'page callback' => 'getmyprivacy',
		     'type' => MENU_CALLBACK,
		     'access arguments' => array('access content'),
	       );
	     return $items;
	     }
	
	
/**
 * Implements hook_form_alter().
 */
function my_webforms_form_alter(&$form, &$form_state, $form_id) {
	
	//dpm($form_id);
	
	//hook newsletter 
	if($form_id=='webform_client_form_133'){
		$form['#validate'][]='my_webforms_form_newsletter_validate';//hook di validazione al momento della sottoscrizione di una newsletter
	}
	//hook newsletter unsubscribe
	if($form_id=='webform_client_form_867') {
		$form['#validate'][]='my_webforms_form_validate_unsubscribe';//hook di validazione al momento della sottoscrizione di una newsletter
	}

	
	$mywebforms_params = array(
		'webform_client_form_133'=>array("submitted"=>"newsletter"),
        );
	
	if (array_key_exists($form_id, $mywebforms_params)) {
		
		drupal_add_js(drupal_get_path('module', 'my_webforms') .'/js/my_webforms.js', "file");
		
		//Rendo nascosto il termine Newsletter che tanto è di default pari a Realestate
		if (isset ($form['submitted']['newsletter']) ) {
			$form['submitted']['newsletter']['#type'] = 'hidden';
		}
		
		if (isset ($form['submitted']['termini_e_condizioni']) ) {
			$form['submitted']['termini_e_condizioni']['accetto_i_termini_e_le_condizioni']['#title'] = t('');
			$form['submitted']['termini_e_condizioni']['accetto_comunicazione_dati_personali']['#title'] = t('');
			$comunicazione_dati_personali = $form['submitted']['termini_e_condizioni']['comunicazione_dati_personali']['#markup'];
			$form['submitted']['termini_e_condizioni']['comunicazione_dati_personali']['#markup'] = '<br>'.t($comunicazione_dati_personali);
		}
		
		//dpm($form);
    
		//if (isset ($form['submitted']['richiesta']['rivista']) ) {
		//$form['submitted']['richiesta']['rivista']['#title'] = t('');
		// }
		
	//Validazione/alterazione dei campi sui telefoni (che se senza suffisso nn vengono esportati bene in excel, in quanto omette eventuale 0 del prefisso telefonico nel formato cella generale
	$form['#validate'][] = 'my_phone_numbers_form_validate'; 	
	
	}
	
	//hook webform_results_download_form
	if($form_id=='webform_results_download_form') {
		
		$form['format']['#default_value'] = 'excel';
		$form['format']['#attributes']['disabled'] = 'TRUE';
		$form['select_options']['select_keys']['#default_value'] = 1;
		$form['select_options']['#collapsible'] = 'FALSE';
		$form['select_options']['select_keys']['#attributes']['disabled'] = 'TRUE';
		$form['range']['#collapsible'] = 'FALSE';
		$form['range']['range_type']['#default_value'] = 'new';
		unset($form['components']['#options']['uid']); unset($form['components']['#default_value'][6]);
		unset($form['components']['#options']['draft']); unset($form['components']['#default_value'][4]);
		unset($form['components']['#options']['username']); unset($form['components']['#default_value'][7]);
		//dpm($form);
	}	

}


function my_webforms_node_view($node, $view_mode, $langcode){
	//dpm($node);
	drupal_add_js(drupal_get_path('module', 'my_webforms') .'/js/my_webforms.js', "file");
	drupal_add_library('system', 'ui.dialog');
}

function getmyprivacy(){

	$nid = 120;// nid pagina privacy
	print drupal_render(node_view(node_load($nid),'full',$_GET['ln']));
	}
	

function my_webforms_form_newsletter_validate($form,&$form_state) {
		////dpm($form);
		//dpm($form_state);
		//dpm($form_state['values']['submitted']);
		//$value_cid_webform=$form_state->data[16][0];
		//dpm(isset($form_state['values']['submitted']['stato']));
		$form_state['values']['submitted']['stato'] = (isset($form_state['values']['submitted']['stato'])) ? $form_state['values']['submitted']['stato'] : '1';
		$dato_webform_univoco=$form_state['values']['submitted']['dati_personali']['email'];
		$stato=1;// corrisponde al cid 18
		$value_cid_webform=$form_state['values']['submitted']['newsletter'];// corrisponde al cid 20 - VId Newsletter = 9
		//dpm($form_state['values']['submitted']['newsletter']);
		$array_controllo=array(array('cid'=>'20','value'=>$value_cid_webform),array('cid'=>'18','value'=>$stato));
		$nid_webform_scelta=$form_state['build_info']['args'][0]->nid;//133 nel caso di newsletter
		$sottoscrizione_esistente="We are sorry but there is already a subscription with this email address to the newsletter " ;
	
		//dpm($form_state['input']['details']['sid']);
		$esito = (!$form_state['input']['details']['sid']) ? my_validation($nid_webform_scelta,$dato_webform_univoco,$array_controllo) : 1;
		//drupal_set_message('nid webform'.$nid_webform_scelta);
		//drupal_set_message('email'.$dato_webform_univoco);
		//drupal_set_message('Array'.$array_controllo);
		//dpm($array_controllo);
		if(!$esito)
		{//se true vuol dire che esiste già la sottoscrizione
			form_set_error(" ",'<div class="submissionexixt">'.t($sottoscrizione_esistente).' <b>'.$form_state['values']['submitted']['newsletter'].'</b></div>');
		}
	  }
	  

function my_phone_numbers_form_validate($form,&$form_state) {
		////dpm($form);
		//dpm($form_state);
		if (substr($form_state['values']['submitted']['dati_personali']['telefono'], 0, 1) != '#') $form_state['values']['submitted']['dati_personali']['telefono'] = '#'.$form_state['values']['submitted']['dati_personali']['telefono'];
		if (substr($form_state['values']['submitted']['dati_personali']['cellulare'], 0, 1) != '#') $form_state['values']['submitted']['dati_personali']['cellulare'] = '#'.$form_state['values']['submitted']['dati_personali']['cellulare'];
		if (substr($form_state['values']['submitted']['dati_personali']['fax'], 0, 1) != '#') $form_state['values']['submitted']['dati_personali']['fax'] = '#'.$form_state['values']['submitted']['dati_personali']['fax'];
	  }	  
	  
	  
/*
cid 18   	stato
cid 7 	 	email
cid 20 	 	newsletter (scelta)
*/
function my_validation($nid_webform_scelta,$dato_webform_univoco,$array_controllo){
	/*
	$value_cid_webform=84; tid della newsletter
	$nid_webform_scelta=133;

	$dato_webform_univoco='gino@g.it';
	$array_controllo=array(array('cid'=>16,'value'=>$value_cid_webform),array('cid'=>23,'value'=>1));
	*/
	$querystring="SELECT ws.sid as sid FROM webform_submissions ws inner join webform_submitted_data wsd on wsd.sid=ws.sid WHERE wsd.cid=7 AND wsd.data='".$dato_webform_univoco."' AND ws.nid=".$nid_webform_scelta;
	$result = db_query($querystring);
	module_load_include('inc', 'webform', 'includes/webform.submissions');

	$submit_trovata=false;
	if($result->rowCount()==0) {
	
		return true;
	}
	foreach($result as $row)
	{	
		//echo " - ".$row->sid ;
		//dpm($row->sid);
		$fr=webform_get_submissions(array('nid' => $nid_webform_scelta,'sid' =>$row->sid));
		$condition=null;
		foreach($array_controllo as $key => $val) 
		{ 
		  $condition[]='("'.$fr[$row->sid]->data[$array_controllo[$key]['cid']][0].'"=="'.$array_controllo[$key]['value'].'") ' ;
		}
		
		$myif=' return  '.implode(" && ",$condition).";";
		if(eval($myif))
		{	//sottoscrizione trovata 
			//controllo che la newsletter è ancora attiva, e update 0 qui questa
			$submit_trovata=true;
			return !$submit_trovata;
		}
		
	}
	return !$submit_trovata;
}


