<?php

// Add company_sites_maps.css file:
drupal_add_css(drupal_get_path('module', 'company_sites_maps') . '/css/company_sites_maps.css');

/**
 * Implements hook_views_api().
 */
function company_sites_maps_views_api() {
    return array(
        'api' => '3.0',
        'path' => drupal_get_path('module', 'company_sites_maps'),
        'template path' => drupal_get_path('module', 'company_sites_maps').'/templates',
    );
}

/**
 * Implements hook_views_default_views().
 */
function company_sites_maps_views_default_views() {
    $path = './' . drupal_get_path('module', 'company_sites_maps') . '/views/*.inc';
    $views = array();
    foreach (glob($path) as $views_filename) {
        require_once($views_filename);
    }
    return $views;
}